name:                test-warp-tls
version:             0.1.0.1
github:              "githubuser/test-warp-tls"
license:             BSD3

description:         Please see the README on Github at <https://github.com/githubuser/test-warp-tls#readme>

dependencies:
- base >= 4.7 && < 5
- servant
- servant-server
- text
- aeson

library:
  source-dirs: src

executables:
  test-warp-tls-exe:
    main:                Main.hs
    source-dirs:         server
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - test-warp-tls
    - warp>=3.2.19
    - warp-tls
    - wai
    - wai-cors
    - wai-logger

  test-warp-client:
    main:                Main.hs
    source-dirs:         client
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - test-warp-tls
    - warp
    - wai
    - bytestring
    - http-media

tests:
  test-warp-tls-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - test-warp-tls
